import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Footer from "./components/footer/Footer";

const inter = Inter({
  subsets: ["latin"],
  fallback: ["Inter, sans-serif"],
  display: "swap",
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
/* 
static way
export const metadata: Metadata = {
  title: "Home - Cleaner",
  description: "Generated by create next app",
  openGraph: {
    title: "Our home - Cleaner",
    description: "Cleaning service template for you home, office, soon...",
    images: ["/assets/logo/cleanlog.png"],
  },
}; */

export const metadata: Metadata = {
  title: "Home - Cleaner",
  description: "Generated by create next app",
  openGraph: {
    title: "Our home - Cleaner",
    description: "Cleaning service template for you home, office, soon...",
    images: ["/assets/logo/cleanlog.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable}  ${geistSans.variable} ${geistMono.variable} antialiased bg-clean-sliver-10`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
